name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

env:
  CSV_URL: "MLproject/train_pca.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 2. Set up Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # 3. Check Env
      - name: Check Env
        run: echo "CSV_URL is $CSV_URL"

      # 4. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      # 5. Run MLflow project
      - name: Run mlflow project
        run: mlflow run MLproject --env-manager=local

      # 6. Install and configure Git LFS
      - name: Setup Git LFS
        run: |
          sudo apt update
          sudo apt install -y git-lfs
          git lfs install
          git lfs track "*.pkl"

      # 7. Setup Git Auth & Commit
      - name: Save mlruns to repo with LFS
        env:
          USERNAME: ${{ secrets.USERNAME }}
          EMAIL:    ${{ secrets.EMAIL }}
        run: |
          git config --global user.name  "${USERNAME}"
          git config --global user.email "${EMAIL}"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          git add -f .gitattributes
          git add -f mlruns/

          git diff --cached --quiet || git commit -m "Save mlruns from CI run using Git LFS"
          git push origin main
